# Generated by Django 5.2 on 2025-06-05 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('INFO', 'Informacja'), ('WARN', 'Ostrzeżenie'), ('ERR', 'Błąd')], default='INFO', max_length=4),
        ),
        migrations.CreateModel(
            name='UserLogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_info', models.BooleanField(default=True)),
                ('log_warning', models.BooleanField(default=True)),
                ('log_error', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
