# Generated by Django 5.2 on 2025-06-05 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0003_log_type_userlogsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('INFO', 'Informacja'), ('WARNING', 'Ostrzeżenie'), ('ERROR', 'Błąd')], default='INFO', max_length=9),
        ),
        migrations.CreateModel(
            name='PhoneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=10, verbose_name='NIP')),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nowy'), ('callback', 'Do ponownego kontaktu'), ('passed', 'Przekazany programiście'), ('rejected', 'Odrzucony'), ('other', 'Inne')], default='new', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_service.tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contact_date'],
            },
        ),
    ]
