# Generated by Django 5.1.7 on 2025-06-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0006_favoritelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelink',
            old_name='url',
            new_name='url_name',
        ),
    ]
