# Generated by Django 5.1.7 on 2025-06-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0007_rename_url_favoritelink_url_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelink',
            old_name='url_name',
            new_name='url',
        ),
    ]
