# Generated by Django 5.2 on 2025-07-02 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0009_usersilentsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_display_limit', models.PositiveSmallIntegerField()),
                ('announcement_display_limit', models.PositiveSmallIntegerField()),
                ('ticket_display_switch', models.BooleanField()),
                ('logs_disaply_switch', models.BooleanField()),
                ('announcement_display_switch', models.BooleanField()),
                ('fast_settings_display_switch', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_page_configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
