# Generated by Django 5.2 on 2025-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0010_infoserviceconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoserviceconfiguration',
            name='announcement_display_limit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='infoserviceconfiguration',
            name='announcement_display_switch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='infoserviceconfiguration',
            name='fast_settings_display_switch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='infoserviceconfiguration',
            name='log_display_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='infoserviceconfiguration',
            name='logs_disaply_switch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='infoserviceconfiguration',
            name='ticket_display_switch',
            field=models.BooleanField(default=True),
        ),
    ]
